name: VPS Temporária com SSH via Serveo (6 horas)

on: [push]

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 horas de timeout

    steps:
      - name: Configurar ambiente
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Gerar chaves SSH
        run: |
          ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/id_rsa

      - name: Mostrar credenciais de acesso
        run: |
          echo "===================== INSTRUÇÕES DE ACESSO ====================="
          echo "----- CHAVE PRIVADA SSH (COLE NO TERMIUS/PUTTY) -----"
          cat ~/.ssh/id_rsa
          echo "----- FIM DA CHAVE PRIVADA -----"
          echo ""
          echo "Aguardando conexão Serveo..."

      - name: Instalar e configurar SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server net-tools
          sudo service ssh start
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh restart

      - name: Estabelecer túnel Serveo (com reconexão automática)
        run: |
          for i in {1..10}; do
            echo "Tentativa $i de conexão com Serveo..."
            ssh -o "ServerAliveInterval 60" -R 80:localhost:22 serveo.net 2>&1 | tee serveo.log &
            sleep 15
            
            if grep -q "Forwarding TCP" serveo.log; then
              echo "=================================================="
              echo "✅ CONEXÃO ESTABELECIDA COM SUCESSO!"
              echo "🔗 URL: serveo.net:$(grep -oE 'Forwarding TCP.+:([0-9]+)' serveo.log | cut -d: -f2)"
              echo "👤 Usuário: $(whoami)"
              echo "⏳ A VPS ficará ativa por 6 horas"
              echo "=================================================="
              break
            else
              pkill ssh
              sleep 5
            fi
          done

          # Manter a VPS ativa por 6 horas (21.600 segundos)
          sleep 21600
          echo "Tempo de execução encerrado. VPS será desativada."

      - name: Verificar status
        run: |
          echo "Verificando conexões ativas:"
          netstat -tulnp
          echo ""
          echo "Processos SSH:"
          ps aux | grep ssh
